### PR TITLE
Add TypeScript type declarations

### PR DESCRIPTION
**Pull request by nicholasgonzalezsc**
This PR adds and bundles a type declaration file with flexbox-react. This allows others using typescript to use the library out of the box.
I also added a test file for the typings.

The only new file that will be copied to dist/ will be index.d.ts

### CODE REVIEW

**Comment by nachoaIvarez** [comment]
@nicholasgonzalezsc: Nick this is great, thank you for PR. Quick question: Does this breaks compatibility of any kind for those not using TS? Asking this because I never used it. Other than that, looks awesome!

**Comment by nicholasgonzalezsc** [comment]
@nachoaIvarez Nope, it doesn't break any functionality, just adds support for ts. With plain javascript, the file that is imported remains the same `main: dist/index.js` (package.json). The new `types: dist/index.d.ts` is for typescript to know the shape of `index.js` as it is compiling and type checking the types of the code that depends on flexbox-react.

**Comment by nicholasgonzalezsc** [comment]
@nachoaIvarez Would it be possible to publish a new version, 4.0.3, so that the types are in npm as well?

**Comment by nachoaIvarez** [comment]
Yes, I was about to do so. I will publish a minor release.

**Comment by nicholasgonzalezsc** [comment]
Awesome, thanks so much!

**Pull request merged**
