### PR TITLE
- Added "className" to typings for typescript

### PR DESCRIPTION
**Pull request by paulspiteri**
- Added .gitignore file to explicitly checkout in lf text mode which is required by the linter (failed on Windows otherwise)

#27

### CODE REVIEW

**Comment by paulspiteri** [comment]
@nachoaIvarez slam it home? 🔢

**Comment by nachoaIvarez** [comment]
Hey @paulspiteri! Thank you for your contribution. I'm currently traveling.
I'll review your change when I'm back. Talk to you then.

**Comment by nachoaIvarez** [comment]
Btw, that's next week.

**Comment by nachoaIvarez** [comment]
What's the purpose of the `.gitattributes` file addition @paulspiteri? Looks good to merge but first I want your explanation for that! Thanks.

**Comment by paulspiteri** [comment]
Added .gitignore file to explicitly checkout in LF text mode which is required by the linter (failed on Windows otherwise)

**Comment by paulspiteri** [comment]
I can take that out if you like.  Probably the linter shouldn't care, though?

**Comment by nachoaIvarez** [comment]
Merged and published @paulspiteri.

**Pull request merged**
