### PR TITLE
Allow zero values

### PR DESCRIPTION
**Pull request by theengineear**
This closes an issue and makes the accepted prop types more flexible. See commit notes for details.

### CODE REVIEW

**Comment by theengineear** [comment]
@nachoaIvarez Does this seem inline with your project? I was looking for an open source module that declaratively (but not magically) implements Flex in React and found yours. Being able to set lengthy values is a requirement for me though.

Thanks for your consideration!

**Comment by theengineear** [comment]
As mentioned in one of the commit messages, I think this should only require a SemVer patch. No proptypes that worked before wouldn't work now and no non-zero, false-y values that shouldn't generate declarations do now.

**Comment by theengineear** [comment]
@AnthonyAstige This will resolve your issue, fyi.

**Comment by theengineear** [comment]
@nachoaIvarez Mind taking a look / considering a merge?

**Comment by nachoaIvarez** [comment]
Sorry for the late response, @theengineear. I was taking a break from OSS. Thank you for your contrib. This looks 👍

**Pull request merged**
