### PR TITLE
Fix SSR by upgrading to styled-components v2

### PR DESCRIPTION
**Pull request by hampusohlsson**
Hey @nachoaIvarez, as mentioned in my comment on #24, SSR is still not working because of `styled-components@1.4.4`. Upgrading to `v2/next` solves this 😄

### CODE REVIEW

**Comment by hampusohlsson** [comment]
Is this a fix / wontfix? @nachoaIvarez

**Comment by nachoaIvarez** [comment]
Sorry for the delay, @hampusohlsson. I arrived from a trip last night. PR looks fine, but I need to ask you to undo [this change](https://github.com/nachoaIvarez/flexbox-react/pull/32/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2L3) since version bumping and publishing is managed with [`np`](https://github.com/sindresorhus/np). Everything else looks 👍.

**Comment by hampusohlsson** [comment]
Awesome, thanks! Let me know if you want me to squash the commits into one?

**Comment by mxstbr** [comment]
We are currently in the process of coming up [with a better API for SSR](https://github.com/styled-components/styled-components/issues/386) that will get built before the full release, so maybe give it a week until we have that done?

**Comment by nachoaIvarez** [comment]
I was expecting that one last comment from @mxstbr before merging. Let's stick with him, @hampusohlsson. Hold up that PR!

**Comment by hampusohlsson** [comment]
Somehow that SSR thread slipped under my radar! Sounds great 👍

**Comment by shalzz** [comment]
Styled components v2 is released. Adapt this to version 2 and merge?

**Comment by hampusohlsson** [comment]
@nachoaIvarez @Shalzz this PR is now styled-components v2 compliant

**Comment by mxstbr** [comment]
Yay! Sorry for the delay in releasing it, though I hope you enjoy v2!

**Review by nachoaIvarez — APPROVED** [review]

**Pull request merged**
